"""empty message

Revision ID: 4638b5289b22
Revises: 1095bc122dd6
Create Date: 2014-12-08 16:49:30.904873

"""

# revision identifiers, used by Alembic.
revision = '4638b5289b22'
down_revision = 'init'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('app_management_port', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('open_port_for_ip_link', sa.String(length=150), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    #op.drop_column('sessions', 'open_port_for_ip_link')
    #op.drop_column('sessions', 'app_management_port')
    ### end Alembic commands ###
